name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo-path:  
    description: 'Repo name'
    required: true
  retaining-days:  
    description: 'Retaining Days'
    required: false
    default: 30

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
