name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repository:  # id of input
    description: 'Repo name'
    required: true
    default: 'repo'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
