name: 'Release tag'
description: 'Create tag by the branch'
inputs:
  sourcebranch:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true

runs:
  using: "composite"
  steps: 
    - name: "Print"
      run: echo "Prinitng - ${{ inputs.sourcebranch }}"
      shell: bash
    
    - uses: actions/checkout@v4
    - if: startsWith(inputs.sourcebranch, 'release/')
      name: Find Release Version From Branch
      id: release_tag_in_branch
      run: | 
            currentBranch="${{ inputs.sourcebranch }}"
            echo "Branch Name - ${currentBranch}"
            extractedVersion=${currentBranch/'release/'}
            echo "Extracted Version - ${extractedVersion}"
            echo "TAG_NAME=$extractedVersion" >> $GITHUB_OUTPUT
            echo "TAG_NAME=$extractedVersion" >> $GITHUB_ENV
      shell: bash

    - name: DEbug 
      run: |
        echo "TAG_NAME ---> ${{ env.TAG_NAME }}"
        echo "TAG_NAME1 ---> ${{ steps.release_tag_in_branch.outputs.TAG_NAME }}"
      shell: bash
      
    - if: ${{ !steps.release_tag_in_branch.outputs.TAG_NAME }} 
      name: Find Release version By Branch
      id: release_type
      run: |
            currentBranch="${{ inputs.sourcebranch }}" 
             if [[ $currentBranch == 'release' ]]; then 
              echo "Identifyed as minor release"
              echo "RELEASE_TYPE=minor" >> $GITHUB_OUTPUT
             elif [[ $currentBranch == hotfix/* ]]; then 
              echo "Identifyed as patch release"
              echo "RELEASE_TYPE=patch" >> $GITHUB_OUTPUT
             else 
              exit 0;
             fi
      shell: bash
      
    - if: ${{ steps.release_type.outputs.RELEASE_TYPE }}
      name: Initiating Next Version Lookup
      id: next_release_tag_lookup
      uses: reecetech/version-increment@2023.10.1
      with:
        use_api: true
        increment: ${{ steps.release_type.outputs.RELEASE_TYPE }}
      shell: bash

    - name: Next Release Version
     id: next_version
     run: echo "TAG_NAME=${{ steps.next_release_tag_lookup.outputs.version }}" >> $GITHUB_OUTPUT
     shell: bash

    - name: Print Tag
     run: | 
            echo "Release Tag - ${{ steps.release_tag_in_branch.outputs.TAG_NAME }}"
            echo "Next Release - ${{ steps.next_version.outputs.TAG_NAME }}"
     shell: bash


