name: 'Release tag'
description: 'Create tag by the branch'
inputs:
  source-branch:
    description: 'Branch name to be tagged'
    required: true
    
outputs:
  tag:
    description: "The Tag"
    value: ${{ steps.create_tag.outputs.tag }}

runs:
  using: "composite"
  steps: 
    - name: "Branch Name"
      run: echo "Branch Name123 - ${{ inputs.source-branch }}"
      shell: bash
    
    - uses: actions/checkout@v4
    - if: startsWith(inputs.source-branch, 'release/')
      name: Find Release Version From Branch
      id: release_tag_in_branch
      run: | 
            currentBranch="${{ inputs.source-branch }}"
            echo "Branch Name - ${currentBranch}"
            extractedVersion=${currentBranch/'release/'}
            echo "Extracted Version - ${extractedVersion}"
            echo "TAG_NAME=$extractedVersion" >> $GITHUB_OUTPUT
            echo "TAG_NAME=$extractedVersion" >> $GITHUB_ENV
      shell: bash
      
    - if: ${{ !steps.release_tag_in_branch.outputs.TAG_NAME }} 
      name: Find Release version By Branch
      id: release_type
      run: |
            currentBranch="${{ inputs.source-branch }}" 
             if [[ $currentBranch == 'release' ]]; then 
              echo "Identifyed as minor release"
              echo "RELEASE_TYPE=minor" >> $GITHUB_OUTPUT
             elif [[ $currentBranch == hotfix/* ]]; then 
              echo "Identifyed as patch release"
              echo "RELEASE_TYPE=patch" >> $GITHUB_OUTPUT
             else 
              exit 0;
             fi
      shell: bash
      
    - if: ${{ steps.release_type.outputs.RELEASE_TYPE }}
      name: Initiating Next Version Lookup
      id: next_release_tag_lookup
      uses: reecetech/version-increment@2023.10.1
      with:
        use_api: true
        increment: ${{ steps.release_type.outputs.RELEASE_TYPE }}

    - name: Next Release Version
      id: next_version
      run: echo "TAG_NAME=${{ steps.next_release_tag_lookup.outputs.version }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Print Tag
      run: | 
            echo "Release Tag - ${{ steps.release_tag_in_branch.outputs.TAG_NAME }}"
            echo "Next Release - ${{ steps.next_version.outputs.TAG_NAME }}"
      shell: bash

    - if: ${{ steps.release_tag_in_branch.outputs.TAG_NAME || steps.next_version.outputs.TAG_NAME }}
      name: Create Tag
      id: create_tag
      env:
       RELEASE_TAG_IN_BRANCH: ${{ steps.release_tag_in_branch.outputs.TAG_NAME }}
       NEXT_TAG: ${{  steps.next_version.outputs.TAG_NAME }}
      run: |
              RELEASING_TAG=$([ $RELEASE_TAG_IN_BRANCH ] && echo "$RELEASE_TAG_IN_BRANCH" || echo "$NEXT_TAG")
              echo "tag=$RELEASING_TAG" >> $GITHUB_OUTPUT
              echo "Next Tag - $RELEASING_TAG"
              git config --global user.name "GitHub Actions"
              git tag -a $RELEASING_TAG -m "Release $RELEASING_TAG"
              git push origin $RELEASING_TAG
      shell: bash


