name: 'Release tag'
description: 'Create tag by the branch'
inputs:
  source-branch:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true

run: 
  using: "composit"
  steps:
    - name: Testing workflow Root
      run: echo "Heloooooo ${{ inputs.source-branch }}"
