name: 'Release tag'
description: 'Create tag by the branch'
inputs:
  sourcebranch:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true

runs:
  using: "composite"
  steps: 
    - name: "Print"
      run: echo "Prinitng - ${{ inputs.sourcebranch }}"
      shell: bash
    
    - uses: actions/checkout@v4
    - if: startsWith(inputs.sourcebranch, 'release/')
      name: Find Release Version From Branch
      id: release_tag_in_branch
      run: | 
            currentBranch="${{ inputs.sourcebranch }}"
            echo "Branch Name - ${currentBranch}"
            extractedVersion=${currentBranch/'release/'}
            echo "Extracted Version - ${extractedVersion}"
            echo "TAG_NAME=$extractedVersion" >> $GITHUB_OUTPUT
            echo "TAG_NAME=$extractedVersion" >> $GITHUB_ENV
      shell: bash

    - name: DEbug 
      run: echo "TAG_NAME ---> ${{ env.TAG_NAME }}"


