name: 'Release tag'
description: 'Create tag by the branch'
inputs:
  source-branch:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true

jobs:
  create_tag:
  runs-on: ubuntu-latest
  steps:
    - name: Testing workflow Root
      run: echo "Heloooooo ${{ inputs.source-branch }}"
