name: 'Release tag'
description: 'Create tag by the branch'
inputs:
  sourcebranch:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true

runs:
  using: "composit"
  steps: 
    - name: Testing workflow Root
      run: echo "Heloooooo ${{ inputs.sourcebranch }}"

#jobs:
#  create_tag:
#  runs-on: ubuntu-latest
#  steps:
#    - name: Testing workflow Root
#      run: echo "Heloooooo ${{ github.event.inputs.source-branch }}"
